In this jupyter I try to assign a numerical value to every card in hearthstone.<br>
The result should be a dictionary where keys are cards names and values are their numbers.


type:<br>
MINION -> 1 - 2000<br>
SPELL -> 2001 - 4000<br>
ENCHANTMENT -> 4001 - 6000<br>
WEAPON -> 6001 - 8000<br>
HERO_POWER -> 8001 - 10000<br>
HERO -> 10001 - 12000 

Within a type there is cardClass:<br>
NEUTRAL -> 1 - 1000<br>
INVALID -> 1001 - 1075<br>
DEATHKNIGHT -> 1076 - 1150<br>
DRUID -> 1151 - 1225<br>
HUNTER -> 1226 - 1300<br>
MAGE -> 1301 - 1375<br>
PALADIN -> 1376 - 1450<br>
PRIEST -> 1451 - 1525<br>
ROGUE -> 1526 - 1600<br>
SHAMAN -> 1601 - 1675<br>
WARLOCK -> 1676 - 1750<br>
WARRIOR -> 1751 - 1825<br>
DREAM -> 1826 - 1900<br>

Within a cardClass cards are sorted by their cost

In [7]:
import numpy as np

In [8]:
current_values = np.ones((6, 13), dtype=int)

next_value = 1
for i in range(6):
    current_values[i, 0] = next_value
    
    next_set = next_value + 1000
    for j in range(1, 13):
        current_values[i, j] = next_set
        next_set = next_set + 75
        
    next_value = next_value + 2000

In [9]:
current_values

array([[    1,  1001,  1076,  1151,  1226,  1301,  1376,  1451,  1526,
         1601,  1676,  1751,  1826],
       [ 2001,  3001,  3076,  3151,  3226,  3301,  3376,  3451,  3526,
         3601,  3676,  3751,  3826],
       [ 4001,  5001,  5076,  5151,  5226,  5301,  5376,  5451,  5526,
         5601,  5676,  5751,  5826],
       [ 6001,  7001,  7076,  7151,  7226,  7301,  7376,  7451,  7526,
         7601,  7676,  7751,  7826],
       [ 8001,  9001,  9076,  9151,  9226,  9301,  9376,  9451,  9526,
         9601,  9676,  9751,  9826],
       [10001, 11001, 11076, 11151, 11226, 11301, 11376, 11451, 11526,
        11601, 11676, 11751, 11826]])

In [10]:
validation_array = np.copy(current_values)

for i in range(6):
    for j in range(12):
        validation_array[i][j] = validation_array[i][j + 1] - 1
     
for i in range(5):   
    validation_array[i][12] = current_values[i + 1][0] - 1

In [11]:
validation_array

array([[ 1000,  1075,  1150,  1225,  1300,  1375,  1450,  1525,  1600,
         1675,  1750,  1825,  2000],
       [ 3000,  3075,  3150,  3225,  3300,  3375,  3450,  3525,  3600,
         3675,  3750,  3825,  4000],
       [ 5000,  5075,  5150,  5225,  5300,  5375,  5450,  5525,  5600,
         5675,  5750,  5825,  6000],
       [ 7000,  7075,  7150,  7225,  7300,  7375,  7450,  7525,  7600,
         7675,  7750,  7825,  8000],
       [ 9000,  9075,  9150,  9225,  9300,  9375,  9450,  9525,  9600,
         9675,  9750,  9825, 10000],
       [11000, 11075, 11150, 11225, 11300, 11375, 11450, 11525, 11600,
        11675, 11750, 11825, 11826]])

In [12]:
import json

data = json.load(open('cards.json'))

In [13]:
to_remove = []
for i in range(len(data)):
    if 'cost' not in data[i]:
        to_remove.append(i)
        
to_remove.reverse()

for i in to_remove:
    data.pop(i)

In [14]:
from operator import itemgetter

#data.sort(key=lambda item: item['cost'])
data.sort(key=itemgetter('cost'))
#new_data = sorted(data, key=itemgetter('cost'))

In [15]:
data[1593]

{'artist': 'Glenn Rane',
 'attack': 8,
 'cardClass': 'NEUTRAL',
 'collectible': True,
 'cost': 20,
 'dbfId': 1372,
 'flavor': 'He gets terrible heartburn.  BECAUSE HE IS FULL OF LAVA.',
 'health': 8,
 'id': 'EX1_620',
 'name': 'Molten Giant',
 'rarity': 'EPIC',
 'text': 'Costs (1) less for each damage your hero has taken.',
 'type': 'MINION'}

In [16]:
from enum import IntEnum


class CardClass(IntEnum):
    NEUTRAL = 0
    INVALID = 1
    DEATHKNIGHT = 2
    DRUID = 3
    HUNTER = 4
    MAGE = 5
    PALADIN = 6
    PRIEST = 7
    ROGUE = 8
    SHAMAN = 9
    WARLOCK = 10
    WARRIOR = 11
    DREAM = 12

In [17]:
class CardType(IntEnum):
    MINION = 0
    SPELL = 1
    ENCHANTMENT = 2
    WEAPON = 3
    HERO_POWER = 4
    HERO = 5

In [18]:
cart_codes = {}

for i in range(len(data)):
    cart_codes[data[i]['name']] = current_values[CardType[data[i]['type']]][CardClass[data[i]['cardClass']]]
    current_values[CardType[data[i]['type']]][CardClass[data[i]['cardClass']]] =\
        current_values[CardType[data[i]['type']]][CardClass[data[i]['cardClass']]] + 1

In [20]:
validation_test = np.greater(validation_array, current_values)

In [21]:
validation_test

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False]])

In [ ]:
import pandas as pd

training_decks = pd.read_json(open('trainingDecks.json'), lines=True)

In [16]:
cart_codes['Voidwalker']

1677

In [21]:
list(training_decks.iloc[0, 0].items())

[('Armorsmith', [2]),
 ('Execute', [2]),
 ('Bash', [2]),
 ('Drywhisker Armorer', [1]),
 ("Dead Man's Hand", [1]),
 ('Shield Block', [1]),
 ('Blood Razor', [2]),
 ('Shield Slam', [2]),
 ('Cornered Sentry', [1]),
 ('Whirlwind', [1]),
 ('Novice Engineer', [2]),
 ('Fierce Monkey', [1]),
 ('Shieldbearer', [1]),
 ('Frostwolf Warlord', [1]),
 ('Mortal Strike', [1]),
 ('Acolyte of Pain', [2]),
 ('Sleep with the Fishes', [1]),
 ('Cleave', [1]),
 ('Scourgelord Garrosh', [1]),
 ('Dirty Rat', [1]),
 ('Unidentified Shield', [2]),
 ('Brawl', [1])]

In [68]:
new_training_decks = [[]]

for index, row in training_decks.iterrows():
    deck_representnion = []
    
    for key, value in row['cards'].items():
        deck_representnion.append(cart_codes[key])
        
        if value[0] == 2:
             deck_representnion.append(cart_codes[key])
             
    deck_representnion.sort()
    new_training_decks.append(deck_representnion)
    
new_training_decks.pop(0)

[]

In [86]:
decks = pd.read_csv('decks.csv', index_col=0)

In [89]:
import pandas as pd

test = pd.DataFrame(new_training_decks, columns=range(1, 31), index=training_decks['deckName'].apply(lambda x: x[0]))
test['Druid'] = decks['Druid']
test['Hunter'] = decks['Hunter']
test['Mage'] = decks['Mage']
test['Paladin'] = decks['Paladin']
test['Priest'] = decks['Priest']
test['Rogue'] = decks['Rogue']
test['Shaman'] = decks['Shaman']
test['Warlock'] = decks['Warlock']
test['Warrior'] = decks['Warrior']

test['prob'] = decks['prob']
test['prob_A1'] = decks['prob_A1']
test['prob_A2'] = decks['prob_A2']
test['prob_B1'] = decks['prob_B1']
test['prob_B2'] = decks['prob_B2']

In [ ]:
test.to_csv('training_decks.csv')

Coding test set:


In [24]:
import pandas as pd

training_decks = pd.read_json(open('testDecks.json'), lines=True)

new_training_decks = [[]]

for index, row in training_decks.iterrows():
    deck_representnion = []
    
    for key, value in row['cards'].items():
        deck_representnion.append(cart_codes[key])
        
        if value[0] == 2:
             deck_representnion.append(cart_codes[key])
             
    deck_representnion.sort()
    new_training_decks.append(deck_representnion)
    
new_training_decks.pop(0)

[]

In [27]:
decks = pd.read_csv('X_test.csv', index_col=0)

In [28]:
import pandas as pd

test = pd.DataFrame(new_training_decks, columns=range(1, 31), index=training_decks['deckName'].apply(lambda x: x[0]))
test['Druid'] = decks['Druid']
test['Hunter'] = decks['Hunter']
test['Mage'] = decks['Mage']
test['Paladin'] = decks['Paladin']
test['Priest'] = decks['Priest']
test['Rogue'] = decks['Rogue']
test['Shaman'] = decks['Shaman']
test['Warlock'] = decks['Warlock']
test['Warrior'] = decks['Warrior']

In [32]:
test.to_csv('X_test_codes.csv')