In this jupyter I try to assign a numerical value to every card in hearthstone.<br>
The result should be a dictionary where keys are cards names and values are their numbers.


type:<br>
MINION -> 1 - 2000<br>
SPELL -> 2001 - 4000<br>
ENCHANTMENT -> 4001 - 6000<br>
WEAPON -> 6001 - 8000<br>
HERO_POWER -> 8001 - 10000<br>
HERO -> 10001 - 12000 

Within a type there is cardClass:<br>
NEUTRAL -> 1 - 1000<br>
INVALID -> 1001 - 1075<br>
DEATHKNIGHT -> 1076 - 1150<br>
DRUID -> 1151 - 1225<br>
HUNTER -> 1226 - 1300<br>
MAGE -> 1301 - 1375<br>
PALADIN -> 1376 - 1450<br>
PRIEST -> 1451 - 1525<br>
ROGUE -> 1526 - 1600<br>
SHAMAN -> 1601 - 1675<br>
WARLOCK -> 1676 - 1750<br>
WARRIOR -> 1751 - 1825<br>
DREAM -> 1826 - 1900<br>

Within a cardClass cards are sorted by their cost

In [1]:
import numpy as np

In [2]:
current_values = np.ones((6, 13), dtype=int)

next_value = 1
for i in range(6):
    current_values[i, 0] = next_value
    
    next_set = next_value + 1000
    for j in range(1, 13):
        current_values[i, j] = next_set
        next_set = next_set + 75
        
    next_value = next_value + 2000

In [3]:
current_values

array([[    1,  1001,  1076,  1151,  1226,  1301,  1376,  1451,  1526,
         1601,  1676,  1751,  1826],
       [ 2001,  3001,  3076,  3151,  3226,  3301,  3376,  3451,  3526,
         3601,  3676,  3751,  3826],
       [ 4001,  5001,  5076,  5151,  5226,  5301,  5376,  5451,  5526,
         5601,  5676,  5751,  5826],
       [ 6001,  7001,  7076,  7151,  7226,  7301,  7376,  7451,  7526,
         7601,  7676,  7751,  7826],
       [ 8001,  9001,  9076,  9151,  9226,  9301,  9376,  9451,  9526,
         9601,  9676,  9751,  9826],
       [10001, 11001, 11076, 11151, 11226, 11301, 11376, 11451, 11526,
        11601, 11676, 11751, 11826]])

In [4]:
validation_array = np.copy(current_values)

for i in range(6):
    for j in range(12):
        validation_array[i][j] = validation_array[i][j + 1] - 1
     
for i in range(5):   
    validation_array[i][12] = current_values[i + 1][0] - 1

In [5]:
validation_array

array([[ 1000,  1075,  1150,  1225,  1300,  1375,  1450,  1525,  1600,
         1675,  1750,  1825,  2000],
       [ 3000,  3075,  3150,  3225,  3300,  3375,  3450,  3525,  3600,
         3675,  3750,  3825,  4000],
       [ 5000,  5075,  5150,  5225,  5300,  5375,  5450,  5525,  5600,
         5675,  5750,  5825,  6000],
       [ 7000,  7075,  7150,  7225,  7300,  7375,  7450,  7525,  7600,
         7675,  7750,  7825,  8000],
       [ 9000,  9075,  9150,  9225,  9300,  9375,  9450,  9525,  9600,
         9675,  9750,  9825, 10000],
       [11000, 11075, 11150, 11225, 11300, 11375, 11450, 11525, 11600,
        11675, 11750, 11825, 11826]])

In [6]:
import json

data = json.load(open('cards.json'))

In [7]:
to_remove = []
for i in range(len(data)):
    if 'cost' not in data[i]:
        to_remove.append(i)
        
to_remove.reverse()

for i in to_remove:
    data.pop(i)

In [8]:
from operator import itemgetter

#data.sort(key=lambda item: item['cost'])
data.sort(key=itemgetter('cost'))
#new_data = sorted(data, key=itemgetter('cost'))

In [9]:
data[1593]

{'artist': 'Glenn Rane',
 'attack': 8,
 'cardClass': 'NEUTRAL',
 'collectible': True,
 'cost': 20,
 'dbfId': 1372,
 'flavor': 'He gets terrible heartburn.  BECAUSE HE IS FULL OF LAVA.',
 'health': 8,
 'id': 'EX1_620',
 'name': 'Molten Giant',
 'rarity': 'EPIC',
 'text': 'Costs (1) less for each damage your hero has taken.',
 'type': 'MINION'}

In [10]:
from enum import IntEnum


class CardClass(IntEnum):
    NEUTRAL = 0
    INVALID = 1
    DEATHKNIGHT = 2
    DRUID = 3
    HUNTER = 4
    MAGE = 5
    PALADIN = 6
    PRIEST = 7
    ROGUE = 8
    SHAMAN = 9
    WARLOCK = 10
    WARRIOR = 11
    DREAM = 12

In [11]:
class CardType(IntEnum):
    MINION = 0
    SPELL = 1
    ENCHANTMENT = 2
    WEAPON = 3
    HERO_POWER = 4
    HERO = 5

In [12]:
cart_codes = {}

for i in range(len(data)):
    cart_codes[data[i]['name']] = current_values[CardType[data[i]['type']]][CardClass[data[i]['cardClass']]]
    current_values[CardType[data[i]['type']]][CardClass[data[i]['cardClass']]] =\
        current_values[CardType[data[i]['type']]][CardClass[data[i]['cardClass']]] + 1

In [15]:
cart_codes

{'Arcane Tyrant': 440,
 'Divine Favor': 3407,
 'Baleful Banker': 98,
 'Grimestreet Smuggler': 159,
 'Shadow Visions': 3476,
 'Murkspark Eel': 1607,
 'Nourish': 3190,
 'Ozruk': 598,
 'Streetwise Investigator': 381,
 'Armorsmith': 1759,
 'Mimic Pod': 3557,
 'Wild Growth': 3165,
 'Rummaging Kobold': 238,
 'Aluneth': 7301,
 'Silverback Patriarch': 165,
 'Cataclysm': 3710,
 'Stand Against Darkness': 3418,
 'Eaglehorn Bow': 7228,
 'Shadow Rager': 1543,
 'Hungry Dragon': 272,
 'Shadowboxer': 1461,
 'Luckydo Buccaneer': 1576,
 'Mechwarper': 99,
 'Murloc Raider': 16,
 'Ghost Light Angler': 1608,
 'Chromaggus': 554,
 'Vulgar Homunculus': 1691,
 'Blood To Ichor': 3757,
 'Eerie Statue': 340,
 'Scarlet Crusader': 175,
 'Fiendish Circle': 3707,
 'Wispering Woods': 3185,
 'Arcane Blast': 3304,
 'Avalanche': 3641,
 'Grimestreet Informant': 62,
 'Flame Imp': 1678,
 'Recycle': 3196,
 'Bane of Doom': 3711,
 'Festeroot Hulk': 1785,
 'Lesser Onyx Spellstone': 3564,
 'Pyros': 1314,
 'Dragon Soul': 7451,
 'D

In [13]:
validation_test = np.greater(validation_array, current_values)

In [14]:
validation_test

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True, False]])

In [15]:
import pandas as pd

training_decks = pd.read_json(open('trainingDecks.json'), lines=True)
training_decks

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>cards</th>
      <th>deckName</th>
      <th>hero</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>{'Armorsmith': [2], 'Execute': [2], 'Bash': [2...</td>
      <td>[deck252103]</td>
      <td>[Warrior]</td>
    </tr>
    <tr>
      <th>1</th>
      <td>{'Twilight Drake': [2], 'Cobalt Scalebane': [2...</td>
      <td>[deck105300]</td>
      <td>[Priest]</td>
    </tr>
    <tr>
      <th>2</th>
      <td>{'Coldlight Seer': [1], 'Grimscale Chum': [1],...</td>
      <td>[deck822100]</td>
      <td>[Paladin]</td>
    </tr>
    <tr>
      <th>3</th>
      <td>{'Malchezaar's Imp': [2], 'Doomguard': [1], 'B...</td>
      <td>[deck829295]</td>
      <td>[Warlock]</td>
    </tr>
    <tr>
      <th>4</th>
      <td>{'Al'Akir the Windlord': [1], 'Nightblade': [1...</td>
      <td>[deck627915]</td>
      <td>[Shaman]</td>
    </tr>
    <tr>
      <th>5</th>
      <td>{'Sprint': [1], 'Deadly Poison': [2], 'Bloodfe...</td>
      <td>[deck741027]</td>
      <td>[Rogue]</td>
    </tr>
    <tr>
      <th>6</th>
      <td>{'Armorsmith': [1], 'Execute': [2], 'Cobalt Sc...</td>
      <td>[deck621127]</td>
      <td>[Warrior]</td>
    </tr>
    <tr>
      <th>7</th>
      <td>{'Cobalt Scalebane': [2], 'Dire Wolf Alpha': [...</td>
      <td>[deck131055]</td>
      <td>[Hunter]</td>
    </tr>
    <tr>
      <th>8</th>
      <td>{'Sen'jin Shieldmasta': [2], 'Bloodfen Raptor'...</td>
      <td>[deck331896]</td>
      <td>[Mage]</td>
    </tr>
    <tr>
      <th>9</th>
      <td>{'Wrath': [2], 'Living Mana': [1], 'Jade Behem...</td>
      <td>[deck200965]</td>
      <td>[Druid]</td>
    </tr>
    <tr>
      <th>10</th>
      <td>{'Armorsmith': [2], 'Execute': [2], 'Battle Ra...</td>
      <td>[deck216709]</td>
      <td>[Warrior]</td>
    </tr>
    <tr>
      <th>11</th>
      <td>{'Felfire Potion': [1], 'Doomguard': [2], 'Blo...</td>
      <td>[deck883366]</td>
      <td>[Warlock]</td>
    </tr>
    <tr>
      <th>12</th>
      <td>{'Cobalt Scalebane': [2], 'Corridor Creeper': ...</td>
      <td>[deck385832]</td>
      <td>[Rogue]</td>
    </tr>
    <tr>
      <th>13</th>
      <td>{'Doomguard': [2], 'Bloodreaver Gul'dan': [1],...</td>
      <td>[deck408307]</td>
      <td>[Warlock]</td>
    </tr>
    <tr>
      <th>14</th>
      <td>{'Al'Akir the Windlord': [1], 'Mana Tide Totem...</td>
      <td>[deck173092]</td>
      <td>[Shaman]</td>
    </tr>
    <tr>
      <th>15</th>
      <td>{'Cobalt Scalebane': [2], 'Southsea Deckhand':...</td>
      <td>[deck969031]</td>
      <td>[Rogue]</td>
    </tr>
    <tr>
      <th>16</th>
      <td>{'Wrath': [2], 'Prince Taldaram': [1], 'Astral...</td>
      <td>[deck731599]</td>
      <td>[Druid]</td>
    </tr>
    <tr>
      <th>17</th>
      <td>{'Doomguard': [2], 'Bloodreaver Gul'dan': [1],...</td>
      <td>[deck787788]</td>
      <td>[Warlock]</td>
    </tr>
    <tr>
      <th>18</th>
      <td>{'Mirror Entity': [2], 'Mana Wyrm': [2], 'Arca...</td>
      <td>[deck985907]</td>
      <td>[Mage]</td>
    </tr>
    <tr>
      <th>19</th>
      <td>{'Mana Wyrm': [2], 'Firelands Portal': [2], 'K...</td>
      <td>[deck973677]</td>
      <td>[Mage]</td>
    </tr>
    <tr>
      <th>20</th>
      <td>{'Wrath': [2], 'Living Mana': [1], 'Jade Behem...</td>
      <td>[deck979384]</td>
      <td>[Druid]</td>
    </tr>
    <tr>
      <th>21</th>
      <td>{'Cobalt Scalebane': [2], 'Corridor Creeper': ...</td>
      <td>[deck973905]</td>
      <td>[Rogue]</td>
    </tr>
    <tr>
      <th>22</th>
      <td>{'Mana Tide Totem': [2], 'Tar Creeper': [2], '...</td>
      <td>[deck671869]</td>
      <td>[Shaman]</td>
    </tr>
    <tr>
      <th>23</th>
      <td>{'Doom

In [16]:
cart_codes['Voidwalker']

1677

In [21]:
list(training_decks.iloc[0, 0].items())

[('Armorsmith', [2]),
 ('Execute', [2]),
 ('Bash', [2]),
 ('Drywhisker Armorer', [1]),
 ("Dead Man's Hand", [1]),
 ('Shield Block', [1]),
 ('Blood Razor', [2]),
 ('Shield Slam', [2]),
 ('Cornered Sentry', [1]),
 ('Whirlwind', [1]),
 ('Novice Engineer', [2]),
 ('Fierce Monkey', [1]),
 ('Shieldbearer', [1]),
 ('Frostwolf Warlord', [1]),
 ('Mortal Strike', [1]),
 ('Acolyte of Pain', [2]),
 ('Sleep with the Fishes', [1]),
 ('Cleave', [1]),
 ('Scourgelord Garrosh', [1]),
 ('Dirty Rat', [1]),
 ('Unidentified Shield', [2]),
 ('Brawl', [1])]

In [68]:
new_training_decks = [[]]

for index, row in training_decks.iterrows():
    deck_representnion = []
    
    for key, value in row['cards'].items():
        deck_representnion.append(cart_codes[key])
        
        if value[0] == 2:
             deck_representnion.append(cart_codes[key])
             
    deck_representnion.sort()
    new_training_decks.append(deck_representnion)
    
new_training_decks.pop(0)

[]

In [69]:
new_training_decks

[[29,
  66,
  73,
  73,
  171,
  171,
  393,
  1759,
  1759,
  1762,
  1763,
  1771,
  3754,
  3756,
  3756,
  3762,
  3766,
  3766,
  3767,
  3771,
  3776,
  3776,
  3777,
  3782,
  3783,
  3787,
  3787,
  7760,
  7760,
  11751],
 [113,
  113,
  123,
  123,
  292,
  292,
  327,
  427,
  427,
  509,
  1452,
  1452,
  1464,
  1464,
  1466,
  1478,
  1478,
  1483,
  1483,
  3458,
  3458,
  3461,
  3469,
  3470,
  3470,
  3476,
  3476,
  3478,
  3478,
  3495],
 [16,
  31,
  31,
  38,
  71,
  133,
  133,
  134,
  183,
  187,
  187,
  294,
  294,
  359,
  427,
  427,
  544,
  1376,
  1378,
  1378,
  1379,
  1379,
  1417,
  3407,
  3407,
  3413,
  3413,
  7380,
  7380,
  7381],
 [13,
  54,
  56,
  56,
  171,
  171,
  172,
  242,
  242,
  286,
  292,
  292,
  532,
  544,
  544,
  565,
  565,
  1677,
  1677,
  1678,
  1681,
  1681,
  1702,
  1705,
  1715,
  1718,
  1718,
  3680,
  3680,
  11676],
 [56,
  56,
  134,
  134,
  259,
  280,
  280,
  284,
  401,
  401,
  404,
  479,
  553,
  578,
  

In [86]:
decks = pd.read_csv('decks.csv', index_col=0)

In [89]:
import pandas as pd

test = pd.DataFrame(new_training_decks, columns=range(1, 31), index=training_decks['deckName'].apply(lambda x: x[0]))
test['Druid'] = decks['Druid']
test['Hunter'] = decks['Hunter']
test['Mage'] = decks['Mage']
test['Paladin'] = decks['Paladin']
test['Priest'] = decks['Priest']
test['Rogue'] = decks['Rogue']
test['Shaman'] = decks['Shaman']
test['Warlock'] = decks['Warlock']
test['Warrior'] = decks['Warrior']

test['prob'] = decks['prob']
test['prob_A1'] = decks['prob_A1']
test['prob_A2'] = decks['prob_A2']
test['prob_B1'] = decks['prob_B1']
test['prob_B2'] = decks['prob_B2']

In [92]:
print(test)

               1     2     3     4     5     6     7     8     9    10  \
deckName                                                                 
deck252103    29    66    73    73   171   171   393  1759  1759  1762   
deck105300   113   113   123   123   292   292   327   427   427   509   
deck822100    16    31    31    38    71   133   133   134   183   187   
deck829295    13    54    56    56   171   171   172   242   242   286   
deck627915    56    56   134   134   259   280   280   284   401   401   
deck741027    69    70    70    79    79   168   174   174   286   286   
deck621127    66    66   171   171   292   292   427   505  1759  1762   
deck131055    31    47    47    49    84    84   134   187   242   242   
deck331896    69    70    70    79    79   168   168   174   174   286   
deck200965   280   280   479  1173  1173  1175  1188  1197  3154  3154   
deck216709    66    66   171   171   178   480   505  1759  1759  1762   
deck883366    11    11   221   294   2

In [ ]:
test.to_csv('training_decks.csv')